#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef TERRIER_SWIFT_H
#define TERRIER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MapboxCoreMaps;
@import ObjectiveC;
@import WhirlyGlobe;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Terrier",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol MTLDevice;
@class MBMCustomLayerRenderParameters;
@protocol MTLCommandBuffer;
@class MTLRenderPassDescriptor;

SWIFT_CLASS("_TtC7Terrier20TerrierMapboxAdapter")
@interface TerrierMapboxAdapter : MaplyRenderControllerOverlay <MBMCustomLayerHost>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)renderingWillStart:(id <MTLDevice> _Nonnull)metalDevice colorPixelFormat:(NSUInteger)colorPixelFormat depthStencilPixelFormat:(NSUInteger)depthStencilPixelFormat;
- (void)render:(MBMCustomLayerRenderParameters * _Nonnull)parameters mtlCommandBuffer:(id <MTLCommandBuffer> _Nonnull)mtlCommandBuffer mtlRenderPassDescriptor:(MTLRenderPassDescriptor * _Nonnull)mtlRenderPassDescriptor;
- (void)renderingWillEnd;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType mapView:(int32_t)mapView SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType trackingMode:(BOOL)trackingMode SWIFT_UNAVAILABLE;
@end

@class TrrVarManifest;

SWIFT_PROTOCOL("_TtP7Terrier22TrrVarManifestDelegate_")
@protocol TrrVarManifestDelegate <NSObject>
/// Controls the order in which <code>manifestDidLoad</code> delegates are called
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
@end

@class TrrService;
@class NSString;
enum TrrInterpolationMode : NSInteger;
@class TrrSourceCadence;
@class UIColor;
@class TrrMinMax;
@class TimeSliceInfo;

SWIFT_PROTOCOL("_TtP7Terrier14TrrIController_")
@protocol TrrIController <NSObject>
/// The name of the source API stack
@property (nonatomic, readonly, strong) TrrService * _Nonnull service;
/// Enable or disable all sources together
@property (nonatomic) BOOL enable;
@property (nonatomic, readonly) BOOL started;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// The currently-displayed level (altitude/elevation/pressure/etc.)
@property (nonatomic, copy) NSString * _Nullable level;
/// The set of available levels
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull availableLevels;
/// The priority determines where the sources are drawn on a map controller
@property (nonatomic) int32_t drawPriority;
/// The priority added for each additional source
@property (nonatomic) NSInteger drawPriorityPerSource;
/// Relative Importance factor
/// Larger values cause the map to load more detailed tiles at a given height
@property (nonatomic) float importanceFactor;
/// The relative scale of the render target (0<scale<=1.0)
@property (nonatomic) float renderScale;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Controls the min/max times and number of data slices to fetch
@property (nonatomic, strong) TrrSourceCadence * _Nonnull sourceCadence;
/// If set, we’ll snap to the nearest frame, rather than interpolating
@property (nonatomic) BOOL snapToFrame;
/// Load all frames or only visible ones
@property (nonatomic) BOOL loadAllFrames;
/// The base color, sets global transparency
@property (nonatomic, strong) UIColor * _Nonnull baseColor;
/// Show lots of debug information
@property (nonatomic) BOOL debugMode;
/// The manifests loaded for sources
@property (nonatomic, readonly, copy) NSArray<TrrVarManifest *> * _Nonnull manifests;
/// Add a delegate to be called (only once) when each source is loaded
- (NSInteger)addLoadedDelegate:(void (^ _Nonnull)(id <TrrIController> _Nonnull, TrrVarManifest * _Nonnull, BOOL))delegate SWIFT_WARN_UNUSED_RESULT;
/// Remove a previously-added delegate
- (void)removeLoadedDelegate:(NSInteger)key;
/// Add a delegate to be called when all sources have loaded
- (NSInteger)addAllLoadedDelegateWithTimeout:(NSTimeInterval)timeout :(void (^ _Nonnull)(id <TrrIController> _Nonnull))delegate;
- (BOOL)removeAllLoadedDelegate:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAllSourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAnySourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAllSourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAnySourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Determine the time span covered by any source
- (TrrMinMax * _Nullable)anyCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Determine the time span covered by all active sources
- (TrrMinMax * _Nullable)allCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Return a line per source, describing the origin
- (NSArray<TimeSliceInfo *> * _Nonnull)getCurrentSlices SWIFT_WARN_UNUSED_RESULT;
/// Start loading and rendering
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
/// Force a reload of the entire layer
- (void)reload;
- (void)stop;
@end


/// Common parts of multi-source variable controllers
SWIFT_CLASS("_TtC7Terrier17TrrBaseController")
@interface TrrBaseController : NSObject <TrrIController, TrrVarManifestDelegate>
@property (nonatomic, readonly, strong) TrrService * _Nonnull service;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic) BOOL enable;
@property (nonatomic, readonly) BOOL started;
@property (nonatomic, readonly, copy) NSArray<TrrVarManifest *> * _Nonnull manifests;
@property (nonatomic, copy) NSString * _Nullable level;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull availableLevels;
@property (nonatomic) int32_t drawPriority;
@property (nonatomic) NSInteger drawPriorityPerSource;
/// Scaling factor for the raw data target
@property (nonatomic) float renderScale;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Relative Importance factor
/// Larger values cause the map to load more detail at a given height
@property (nonatomic) float importanceFactor;
@property (nonatomic, strong) TrrSourceCadence * _Nonnull sourceCadence;
@property (nonatomic) BOOL snapToFrame;
/// Load all frames or only the visible ones
@property (nonatomic) BOOL loadAllFrames;
@property (nonatomic, strong) UIColor * _Nonnull baseColor;
@property (nonatomic) BOOL debugMode;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// Add a delegate to be called when all sources have loaded, successfully or otherwise.
/// These delegates are one-shot, and must be added again if they are to be called on reloads.
- (NSInteger)addLoadedDelegate:(void (^ _Nonnull)(id <TrrIController> _Nonnull, TrrVarManifest * _Nonnull, BOOL))delegate SWIFT_WARN_UNUSED_RESULT;
/// Remove a previously-added delegate
- (void)removeLoadedDelegate:(NSInteger)key;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAllSourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAnySourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAllSourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAnySourcesValid SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)addAllLoadedDelegateWithTimeout:(NSTimeInterval)timeout :(void (^ _Nonnull)(id <TrrIController> _Nonnull))delegate;
- (BOOL)removeAllLoadedDelegate:(NSInteger)key SWIFT_WARN_UNUSED_RESULT;
- (TrrMinMax * _Nullable)anyCoverageSpan SWIFT_WARN_UNUSED_RESULT;
- (TrrMinMax * _Nullable)allCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Return the time slices currently being used by the control.
- (NSArray<TimeSliceInfo *> * _Nonnull)getCurrentSlices SWIFT_WARN_UNUSED_RESULT;
/// Force a reload of the entire layer
- (void)reload;
/// Notify the source before the controller so that the frames are up-to-date
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// This is used to represent the time slices being displayed by a given control.
/// It’s a class used in getCurrentSlices()
SWIFT_CLASS("_TtCC7Terrier17TrrBaseController13TimeSliceInfo")
@interface TimeSliceInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Cache cleaner is invoked per source to clean up unused  data.
/// This isn’t typically an object you need to interact with.
SWIFT_CLASS("_TtC7Terrier15TrrCacheCleaner")
@interface TrrCacheCleaner : NSObject
/// Start removing old files
- (void)start;
/// Stop removing old files
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Used to encapsulate a data source (e.g. HRRR, GFS).
SWIFT_CLASS("_TtC7Terrier13TrrDataSource")
@interface TrrDataSource : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;

SWIFT_CLASS("_TtC7Terrier8TrrError")
@interface TrrError : NSError
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


@class TrrColorMap;

SWIFT_PROTOCOL("_TtP7Terrier20TrrIPrecipController_")
@protocol TrrIPrecipController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier19TrrIRadarController_")
@protocol TrrIRadarController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier27TrrISingleChannelController_")
@protocol TrrISingleChannelController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier25TrrITemperatureController_")
@protocol TrrITemperatureController <TrrISingleChannelController>
@end


SWIFT_PROTOCOL("_TtP7Terrier15TrrITimeTracker_")
@protocol TrrITimeTracker
@property (nonatomic, readonly) NSTimeInterval curEpoch;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)play;
- (void)poke;
- (void)addDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Pass in an epoch and return the value interpolated along our range.
/// This is useful for a slider.
- (double)interpolateSimpleWithEpoch:(NSTimeInterval)epoch SWIFT_WARN_UNUSED_RESULT;
- (void)removeDelegateWithDelegate:(NSObject * _Nonnull)delegate;
- (void)shutdown;
@end


SWIFT_PROTOCOL("_TtP7Terrier22TrrTimeTrackerDelegate_")
@protocol TrrTimeTrackerDelegate <NSObject>
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

@class MaplyTexture;

SWIFT_PROTOCOL("_TtP7Terrier18TrrIWindController_")
@protocol TrrIWindController <TrrIController, TrrTimeTrackerDelegate>
/// Enable wind trails.  Independent of the velocity layer.
@property (nonatomic) BOOL enableTrails;
/// Total number of points in the trails.   This determines the size of the buffers used and the memory requirement.
@property (nonatomic) NSInteger trailPoints;
/// The largest allowable value of <code>maxTrailCount</code>, as determined by the memory reserved by <code>trailPoints</code>.
/// The number of trails is limited to <code>trailPoints</code> divided by the number of trail points in a buffer, <code>maxTrailSize</code>
@property (nonatomic, readonly) NSInteger maxMaxTrailCount;
/// Limit the number of trails to a number smaller than the limit as determined above.
/// This does not reduce memory usage, but may improve rendering framerate.
@property (nonatomic) NSInteger maxTrailCount;
/// Minimum lifetime of trails in seconds.
/// Trail lifetimes are set to a random value between the min and max to avoid excessive visual “flocking”
@property (nonatomic) NSTimeInterval trailLifetimeMin;
/// Max lifetime of trails in seconds
@property (nonatomic) NSTimeInterval trailLifetimeMax;
/// Limit the number of points in a trail to a value smaller than the space reserved.
@property (nonatomic, readonly) NSInteger maxTrailSize;
/// This value sets the lower limit of the number of points that must be established in a trail.  If the trail reaches the edge
/// of the screen or turns too sharply, it will be discarded and the trail will be set up in a new location on the next frame.
@property (nonatomic) NSInteger minTrailSize;
/// Width of trails in pixels
@property (nonatomic) float trailWidth;
/// Length of each trail cell in pixels.
@property (nonatomic) float trailAdvanceRate;
/// Maximum turn to allow per point (radians)
/// Only applies when more restrictive than the limit calculated from <code>atan(advance / width)</code>
@property (nonatomic) float turnAngleLimit;
/// Maximum cumulative under-turn before stopping trail advance (sum of dot-products)
@property (nonatomic) float turnErrorLimit;
/// The texture appears this many times along the trail, i.e., texture Y coordinates run from 0..N.
@property (nonatomic) float texPeriod;
/// Only show every Nth texture instance, assuming <code>texPeriod</code> is larger.
/// e.g., <code>texPeriod=4</code> and <code>texInterval=2</code> would split the length of the trail into four parts and show the texture in
/// the first and third of those parts.
@property (nonatomic) NSInteger texInterval;
/// Rate of texture motion (trail lengths / s)
/// The texture Y coordinate shifts by this amount every second, cycling the application of the texture along the trail.
/// May be negative to reverse the direction of motion. (no, you wouldn’t want to do that)
@property (nonatomic) float texRate;
/// Effect of velocity on tex rate
/// 0: no effect, 1: max velocity = 2x texture rate, 2: max velocity = 3x texture rate, …
@property (nonatomic) float texVelRate;
/// Exponential base of velocity effect, 1 = linear.
/// Nearer to base == 0, the effect increases rapidly near zero velocity then levels off near the maximum.
/// For larger values above 1, the effect increases slowly near zero and more rapidly near the maximum.
@property (nonatomic) float texVelExp;
/// Side-to-side texture offset.  By default, the texture will be centered on the trail, aligned such that the X-axis
/// is perpendicular, with 0 at the left and 1 at the right.
@property (nonatomic) float texOffsetX;
/// Front-to-back texture offset.  Shifts the starting point of the texture placement described by <code>texPeriod</code> and <code>texRate</code>
@property (nonatomic) float texOffsetY;
/// Smallest velocity to consider having a meaningful direction
@property (nonatomic) float minVelocity;
/// Fade-in time when a new trail is established, in seconds.
@property (nonatomic) NSTimeInterval fadeIn;
/// Fade-out time when a trail expires, in seconds.
@property (nonatomic) NSTimeInterval fadeOut;
/// How quickly zooming causes established trails to expire.
/// At 1, the remaining time for a trail is reduced by the ratio between the new and old scale.
@property (nonatomic) float scaleResetFactor;
/// Log base for shape modulation function
@property (nonatomic) float shapeParamB;
/// Exponent for shape modulation function
@property (nonatomic) float shapeParamP;
/// Limit for shape modulation function
@property (nonatomic) float shapeParamS;
/// Base color and alpha multiplier for trails
@property (nonatomic, strong) UIColor * _Nonnull trailColor;
/// Color map for trails (including alpha opacity)
@property (nonatomic, strong) TrrColorMap * _Nullable trailColorMap;
/// If true, the trail color map is scaled to the source data range
@property (nonatomic) BOOL scaleTrailColorMap;
/// Apply a new trail color map, optionally scaling [0,1] to the source data range
- (void)setTrailColorMap:(TrrColorMap * _Nullable)_ scaleToRange:(BOOL)scaleToRange;
/// Primary texture for trails (when not using arrows)
@property (nonatomic, strong) MaplyTexture * _Nullable trailTexture;
/// Reset all existing trails over the following time interval.
- (void)resetTrailsWithOverTime:(NSTimeInterval)overTime;
/// Snap to time frames.
/// True to only show a single time at once, switching abruptly when the target time reaches half way between frames.
/// False to interpolate between times.
@property (nonatomic) BOOL animationSnap;
/// Get or override the display of time animation.
/// This overrides the animating state of the time tracker. Use <code>resetAnimatingTime</code> to restore that.
@property (nonatomic) BOOL isAnimatingTime;
/// Reset to using animation state from time tracker
- (void)resetAnimatingTime;
/// If true, fixed arrows are shown instead of wind trails while animating through time.
@property (nonatomic) BOOL animationArrows;
/// If arrows are enabled, this is the texture used. (it doesn’t have to be an arrow).
/// The texture colors will be multiplied through the trail color map, so the texture should be white.
@property (nonatomic, strong) MaplyTexture * _Nullable arrowTexture;
/// The fraction of trails to convert into arrows.  All of them is really dense.
@property (nonatomic) float arrowShowFrac;
/// Length of the arrows (pixels)
@property (nonatomic) float arrowLength;
/// Width of the arrows (pixels)
@property (nonatomic) float arrowWidth;
/// Enable the background layer of wind velocity.  Independent of wind trails.
@property (nonatomic) BOOL enableVelocity;
/// Mapping of wind velocities to colors for the background layer.
@property (nonatomic, strong) TrrColorMap * _Nullable velocityColorMap;
/// If true, the velocity color map is scaled to the source data range
@property (nonatomic) BOOL scaleVelocityColorMap;
/// Apply a new velocity color map, optionally scaling [0,1] to the source data range
- (void)setVelocityColorMap:(TrrColorMap * _Nullable)_ scaleToRange:(BOOL)scaleToRange;
/// Interpolation mode for rendering the off-screen variable target to the screen.
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
/// Whether to use our custom interpolation shader (true) or the built-in Metal interpolator (false)
/// to sample wind data for velocity rendering.
@property (nonatomic) BOOL visualInterpCustom;
/// The interpolation mode used for rendering data into the off-screen variable target.
/// Data interpolation always uses the custom, no-data-aware interpolation implementation.
/// In practice, this can use the slower bicubic interpolation  because <code>TrrIVarController.renderScale</code>
/// reduces the amount of data being processed.
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
/// Opacity factor blended into the alpha channel of the colors used for both trails and velocity
@property (nonatomic) float opacity;
/// If set, we’ll do data values at the center of the screen
@property (nonatomic) BOOL centerSampling;
/// Return two values for wind (U and V) or nothing
- (NSArray<NSNumber *> * _Nonnull)getCenterSample SWIFT_WARN_UNUSED_RESULT;
/// Offline rendering mode changes a little output math
@property (nonatomic) BOOL offlineMode;
@end

typedef SWIFT_ENUM(NSInteger, TrrInterpolationMode, open) {
  TrrInterpolationModeNearest = 0,
  TrrInterpolationModeBilinear = 1,
  TrrInterpolationModeBicubic = 2,
};


/// Displays a loading progress bar under whatever parent UIView you give it.
SWIFT_CLASS("_TtC7Terrier17TrrLoaderProgress")
@interface TrrLoaderProgress : NSObject
/// Start tracking loading and rendering to the tracking image
- (void)start;
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7Terrier9TrrMinMax")
@interface TrrMinMax : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Precipitation controller displays precipitation type data.
SWIFT_CLASS("_TtC7Terrier19TrrPrecipController")
@interface TrrPrecipController : TrrBaseController <TrrIPrecipController, TrrTimeTrackerDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// Set the color map used for display.  This will map from precipitation types to colors.
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end


/// Radar overlay
SWIFT_CLASS("_TtC7Terrier18TrrRadarController")
@interface TrrRadarController : TrrBaseController <TrrIRadarController, TrrTimeTrackerDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

@protocol TrrServiceDelegate;

/// Access to the Terrier Service.  By default this points to a public stack, but you may
/// have your own modifications (e.g. CDNs, authorization, etc).
SWIFT_CLASS("_TtC7Terrier10TrrService")
@interface TrrService : NSObject
@property (nonatomic, copy) NSString * _Nonnull stackName;
@property (nonatomic, readonly, copy) NSString * _Nonnull baseURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull manifestURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull tileURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull vectorURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull mapURL;
@property (nonatomic, readonly) NSInteger apiVersion;
@property (nonatomic, strong) id <TrrServiceDelegate> _Nullable delegate;
- (nonnull instancetype)initWithStackName:(NSString * _Nonnull)stackName OBJC_DESIGNATED_INITIALIZER;
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Fill in this protocol to be notified when the TrrService is ready.
SWIFT_PROTOCOL("_TtP7Terrier18TrrServiceDelegate_")
@protocol TrrServiceDelegate <NSObject>
- (void)serviceReadyWithService:(TrrService * _Nonnull)service;
- (void)serviceFailed;
@end


/// Generic controller for single-channel data like temperature
SWIFT_CLASS("_TtC7Terrier26TrrSingleChannelController")
@interface TrrSingleChannelController : TrrBaseController <TrrISingleChannelController, TrrTimeTrackerDelegate>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end


/// Used to describe how many time slices of data and over what range.
/// The actual data manifest needs to be fetched with this in mind.
SWIFT_CLASS("_TtC7Terrier16TrrSourceCadence")
@interface TrrSourceCadence : NSObject
/// The oldest data to consider, relative to the current time
@property (nonatomic, readonly) NSTimeInterval minTimeOffset;
/// The newest data to consider, relative to the current time
@property (nonatomic, readonly) NSTimeInterval maxTimeOffset;
/// The maximum number of time slices (frames) to consider
@property (nonatomic, readonly) NSInteger maxTimeSlices;
/// If the cadence has been resolved, this is set to when
@property (nonatomic, readonly) NSTimeInterval now;
/// Sort out absolute time from relative time and return it
- (TrrSourceCadence * _Nonnull)resolve SWIFT_WARN_UNUSED_RESULT;
/// Clip against the other cadence and return the results
- (TrrSourceCadence * _Nonnull)clip:(TrrSourceCadence * _Nullable)clip SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithMinTimeOffset:(NSTimeInterval)minTimeOffset maxTimeOffset:(NSTimeInterval)maxTimeOffset maxTimeSlices:(NSInteger)maxTimeSlices;
- (nonnull instancetype)init;
@end


/// Temperature overlay
SWIFT_CLASS("_TtC7Terrier24TrrTemperatureController")
@interface TrrTemperatureController : TrrSingleChannelController <TrrITemperatureController>
@end

@protocol MaplyRenderControllerProtocol;

/// Time Tracker is used to set and update the displayed time amongst a group
/// of delegates.  You can add or remove delegates to the list that get notified interactively.
/// In general, when the time changes, the delegates are notified.
SWIFT_CLASS("_TtC7Terrier14TrrTimeTracker")
@interface TrrTimeTracker : MaplyActiveObject <TrrITimeTracker>
/// Current time for display.  This is what the Tracker is telling all the delegates is the current time.
/// This may be updated externally, or it may be updated as part of an ongoing play.
/// Time is in seconds since 1970.
@property (nonatomic) NSTimeInterval curEpoch;
/// Return true if we’re animating.
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
/// Start animating if we’re not already.
- (void)play;
/// Send a new round of updates to watchers.
/// You may want to do this if you’ve added a new one, though the Tracker will handle that for you.
- (void)poke;
/// Pass in an epoch and return the value interpolated along our range.
/// This is useful for a slider, where the returned value will be in the range 0 to 1.
- (double)interpolateSimpleWithEpoch:(NSTimeInterval)epoch SWIFT_WARN_UNUSED_RESULT;
/// Add a delegate watcher for changes to the values.
/// The delegate will get called with every change to the value, including during an active play().
/// As such, you might want to throttle updates on your side if they’re expensive.
- (void)addDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Remove a delegate watcher.
/// Delegate will no longer be called for Tracker events.
- (void)removeDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Stop sending updates to delegates.
- (void)shutdown;
- (BOOL)hasUpdate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithViewController:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class MaplyBaseViewController;
@class NSData;
@class MaplyRenderTarget;

/// The Variable Controler marshalls data sources for a given
/// variable.
SWIFT_CLASS("_TtC7Terrier16TrrVarController")
@interface TrrVarController : NSObject <MaplySnapshotDelegate>
- (BOOL)needSnapshot:(NSTimeInterval)now viewC:(MaplyBaseViewController * _Nonnull)viewC SWIFT_WARN_UNUSED_RESULT;
- (void)snapshot:(NSData * _Nonnull)snapshotData;
- (MaplyRenderTarget * _Nullable)renderTarget SWIFT_WARN_UNUSED_RESULT;
- (CGRect)snapshotRect SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The manifest gives us details on a given variable (e.g. Temperature)
/// from a particular source (e.g. GFS).  This includes the spatial extents,
/// details about its encoding, and the time slices available.
SWIFT_CLASS("_TtC7Terrier14TrrVarManifest")
@interface TrrVarManifest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC7Terrier14TrrVarManifest9TimeSlice")
@interface TimeSlice : NSObject
@property (nonatomic, readonly) NSTimeInterval forecastEpoch;
@property (nonatomic, readonly) NSTimeInterval runEpoch;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The Variable Source handles the logic for fetching data from a specific
/// data source (e.g. HRRR, 2m_temperature) and rendering it to screen space
SWIFT_CLASS("_TtC7Terrier12TrrVarSource")
@interface TrrVarSource : MaplyActiveObject <TrrTimeTrackerDelegate, TrrVarManifestDelegate>
/// Notify us before the controller so that the frames are up-to-date
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
- (nonnull instancetype)initWithViewController:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Wind Controller handles the visual display of the wind surface and particles.
SWIFT_CLASS("_TtC7Terrier17TrrWindController")
@interface TrrWindController : TrrBaseController <TrrIWindController>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// Enable wind trails
@property (nonatomic) BOOL enableTrails;
/// Enable velocity background
@property (nonatomic) BOOL enableVelocity;
@property (nonatomic) BOOL isAnimatingTime;
- (void)resetAnimatingTime;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) BOOL animationSnap;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Total number of points (not trails)
@property (nonatomic) NSInteger trailPoints;
/// Width of trails in pixels
@property (nonatomic) float trailWidth;
/// Length of trail cells in pixels
@property (nonatomic) float trailAdvanceRate;
/// Maximum turn to allow per segment (radians)
@property (nonatomic) float turnAngleLimit;
/// Maximum cumulative under-turn before stopping trail advance (sum of dot-products)
@property (nonatomic) float turnErrorLimit;
/// Base lifetime of trails
@property (nonatomic) NSTimeInterval trailLifetimeMin;
/// Fractional lifetime variation
@property (nonatomic) NSTimeInterval trailLifetimeMax;
/// Number of texture applications along the trail
@property (nonatomic) float texPeriod;
/// Rate of texture motion (trail lengths / s)
@property (nonatomic) float texRate;
/// Effect of velocity on tex rate
/// 0: no effect, 1: max velocity = 2x texture rate, 2: max velocity = 3x texture rate
@property (nonatomic) float texVelRate;
/// Exponent on velocity effect
/// 1: linear, 0.1: 0.5=>0.76, 0.01: 0.5=>0.9
@property (nonatomic) float texVelExp;
/// Texture offsets
@property (nonatomic) float texOffsetX;
@property (nonatomic) float texOffsetY;
/// Only show every Nth texture instance
@property (nonatomic) NSInteger texInterval;
/// Don’t set up very short trails, e.g., if we hit the edge of available data
@property (nonatomic) NSInteger minTrailSize;
@property (nonatomic, readonly) NSInteger maxTrailSize;
@property (nonatomic, readonly) NSInteger maxMaxTrailCount;
@property (nonatomic) NSInteger maxTrailCount;
@property (nonatomic) float minVelocity;
@property (nonatomic) NSTimeInterval fadeIn;
@property (nonatomic) NSTimeInterval fadeOut;
@property (nonatomic) float scaleResetFactor;
@property (nonatomic) float shapeParamB;
@property (nonatomic) float shapeParamP;
@property (nonatomic) float shapeParamS;
@property (nonatomic, strong) UIColor * _Nonnull trailColor;
@property (nonatomic, strong) TrrColorMap * _Nullable trailColorMap;
@property (nonatomic) BOOL scaleTrailColorMap;
- (void)setTrailColorMap:(TrrColorMap * _Nullable)map scaleToRange:(BOOL)scaleToRange;
@property (nonatomic, strong) MaplyTexture * _Nullable trailTexture;
@property (nonatomic, strong) MaplyTexture * _Nullable arrowTexture;
/// Whether to show static arrows in place of trails while animating timeslices
@property (nonatomic) BOOL animationArrows;
/// The fraction of trails to show as arrows
@property (nonatomic) float arrowShowFrac;
/// Length of arrows (pixels)
@property (nonatomic) float arrowLength;
/// Width of arrows (pixels)
@property (nonatomic) float arrowWidth;
/// Offline mode changes the output logic a little
@property (nonatomic) BOOL offlineMode;
@property (nonatomic, strong) TrrColorMap * _Nullable velocityColorMap;
@property (nonatomic) BOOL scaleVelocityColorMap;
- (void)setVelocityColorMap:(TrrColorMap * _Nullable)map scaleToRange:(BOOL)scaleToRange;
@property (nonatomic) float opacity;
- (void)resetTrailsWithOverTime:(NSTimeInterval)overTime;
+ (id <TrrIWindController> _Nonnull)createWithLevel:(NSString * _Nullable)level service:(TrrService * _Nonnull)service tracker:(id <TrrITimeTracker> _Nonnull)tracker viewC:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_WARN_UNUSED_RESULT;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// Set if you want an up to date center value sample.
/// There’s a performance cost, so we need to turn it on.
@property (nonatomic) BOOL centerSampling;
/// Return a sample from the middle fo the screen.
- (NSArray<NSNumber *> * _Nonnull)getCenterSample SWIFT_WARN_UNUSED_RESULT;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef TERRIER_SWIFT_H
#define TERRIER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MapboxCoreMaps;
@import ObjectiveC;
@import WhirlyGlobe;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Terrier",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol MTLDevice;
@class MBMCustomLayerRenderParameters;
@protocol MTLCommandBuffer;
@class MTLRenderPassDescriptor;

SWIFT_CLASS("_TtC7Terrier20TerrierMapboxAdapter")
@interface TerrierMapboxAdapter : MaplyRenderControllerOverlay <MBMCustomLayerHost>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)renderingWillStart:(id <MTLDevice> _Nonnull)metalDevice colorPixelFormat:(NSUInteger)colorPixelFormat depthStencilPixelFormat:(NSUInteger)depthStencilPixelFormat;
- (void)render:(MBMCustomLayerRenderParameters * _Nonnull)parameters mtlCommandBuffer:(id <MTLCommandBuffer> _Nonnull)mtlCommandBuffer mtlRenderPassDescriptor:(MTLRenderPassDescriptor * _Nonnull)mtlRenderPassDescriptor;
- (void)renderingWillEnd;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType mapView:(int32_t)mapView SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithSize:(CGSize)size mode:(MaplyRenderType)renderType trackingMode:(BOOL)trackingMode SWIFT_UNAVAILABLE;
@end

@class TrrVarManifest;

SWIFT_PROTOCOL("_TtP7Terrier22TrrVarManifestDelegate_")
@protocol TrrVarManifestDelegate <NSObject>
/// Controls the order in which <code>manifestDidLoad</code> delegates are called
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
@end

@class TrrService;
@class NSString;
enum TrrInterpolationMode : NSInteger;
@class TrrSourceCadence;
@class UIColor;
@class TrrMinMax;
@class TimeSliceInfo;

SWIFT_PROTOCOL("_TtP7Terrier14TrrIController_")
@protocol TrrIController <NSObject>
/// The name of the source API stack
@property (nonatomic, readonly, strong) TrrService * _Nonnull service;
/// Enable or disable all sources together
@property (nonatomic) BOOL enable;
@property (nonatomic, readonly) BOOL started;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// The currently-displayed level (altitude/elevation/pressure/etc.)
@property (nonatomic, copy) NSString * _Nullable level;
/// The set of available levels
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull availableLevels;
/// The priority determines where the sources are drawn on a map controller
@property (nonatomic) int32_t drawPriority;
/// The priority added for each additional source
@property (nonatomic) NSInteger drawPriorityPerSource;
/// Relative Importance factor
/// Larger values cause the map to load more detailed tiles at a given height
@property (nonatomic) float importanceFactor;
/// The relative scale of the render target (0<scale<=1.0)
@property (nonatomic) float renderScale;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Controls the min/max times and number of data slices to fetch
@property (nonatomic, strong) TrrSourceCadence * _Nonnull sourceCadence;
/// If set, we’ll snap to the nearest frame, rather than interpolating
@property (nonatomic) BOOL snapToFrame;
/// Load all frames or only visible ones
@property (nonatomic) BOOL loadAllFrames;
/// The base color, sets global transparency
@property (nonatomic, strong) UIColor * _Nonnull baseColor;
/// Show lots of debug information
@property (nonatomic) BOOL debugMode;
/// The manifests loaded for sources
@property (nonatomic, readonly, copy) NSArray<TrrVarManifest *> * _Nonnull manifests;
/// Add a delegate to be called (only once) when each source is loaded
- (NSInteger)addLoadedDelegate:(void (^ _Nonnull)(id <TrrIController> _Nonnull, TrrVarManifest * _Nonnull, BOOL))delegate SWIFT_WARN_UNUSED_RESULT;
/// Remove a previously-added delegate
- (void)removeLoadedDelegate:(NSInteger)key;
/// Add a delegate to be called when all sources have loaded
- (NSInteger)addAllLoadedDelegateWithTimeout:(NSTimeInterval)timeout :(void (^ _Nonnull)(id <TrrIController> _Nonnull))delegate;
- (BOOL)removeAllLoadedDelegate:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAllSourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAnySourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAllSourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAnySourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Determine the time span covered by any source
- (TrrMinMax * _Nullable)anyCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Determine the time span covered by all active sources
- (TrrMinMax * _Nullable)allCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Return a line per source, describing the origin
- (NSArray<TimeSliceInfo *> * _Nonnull)getCurrentSlices SWIFT_WARN_UNUSED_RESULT;
/// Start loading and rendering
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
/// Force a reload of the entire layer
- (void)reload;
- (void)stop;
@end


/// Common parts of multi-source variable controllers
SWIFT_CLASS("_TtC7Terrier17TrrBaseController")
@interface TrrBaseController : NSObject <TrrIController, TrrVarManifestDelegate>
@property (nonatomic, readonly, strong) TrrService * _Nonnull service;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic) BOOL enable;
@property (nonatomic, readonly) BOOL started;
@property (nonatomic, readonly, copy) NSArray<TrrVarManifest *> * _Nonnull manifests;
@property (nonatomic, copy) NSString * _Nullable level;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull availableLevels;
@property (nonatomic) int32_t drawPriority;
@property (nonatomic) NSInteger drawPriorityPerSource;
/// Scaling factor for the raw data target
@property (nonatomic) float renderScale;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Relative Importance factor
/// Larger values cause the map to load more detail at a given height
@property (nonatomic) float importanceFactor;
@property (nonatomic, strong) TrrSourceCadence * _Nonnull sourceCadence;
@property (nonatomic) BOOL snapToFrame;
/// Load all frames or only the visible ones
@property (nonatomic) BOOL loadAllFrames;
@property (nonatomic, strong) UIColor * _Nonnull baseColor;
@property (nonatomic) BOOL debugMode;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// Add a delegate to be called when all sources have loaded, successfully or otherwise.
/// These delegates are one-shot, and must be added again if they are to be called on reloads.
- (NSInteger)addLoadedDelegate:(void (^ _Nonnull)(id <TrrIController> _Nonnull, TrrVarManifest * _Nonnull, BOOL))delegate SWIFT_WARN_UNUSED_RESULT;
/// Remove a previously-added delegate
- (void)removeLoadedDelegate:(NSInteger)key;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAllSourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded, but don’t wait
- (BOOL)areAnySourcesLoaded SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAllSourcesValid SWIFT_WARN_UNUSED_RESULT;
/// Check if all the sources are loaded successfully
- (BOOL)areAnySourcesValid SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)addAllLoadedDelegateWithTimeout:(NSTimeInterval)timeout :(void (^ _Nonnull)(id <TrrIController> _Nonnull))delegate;
- (BOOL)removeAllLoadedDelegate:(NSInteger)key SWIFT_WARN_UNUSED_RESULT;
- (TrrMinMax * _Nullable)anyCoverageSpan SWIFT_WARN_UNUSED_RESULT;
- (TrrMinMax * _Nullable)allCoverageSpan SWIFT_WARN_UNUSED_RESULT;
/// Return the time slices currently being used by the control.
- (NSArray<TimeSliceInfo *> * _Nonnull)getCurrentSlices SWIFT_WARN_UNUSED_RESULT;
/// Force a reload of the entire layer
- (void)reload;
/// Notify the source before the controller so that the frames are up-to-date
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// This is used to represent the time slices being displayed by a given control.
/// It’s a class used in getCurrentSlices()
SWIFT_CLASS("_TtCC7Terrier17TrrBaseController13TimeSliceInfo")
@interface TimeSliceInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Cache cleaner is invoked per source to clean up unused  data.
/// This isn’t typically an object you need to interact with.
SWIFT_CLASS("_TtC7Terrier15TrrCacheCleaner")
@interface TrrCacheCleaner : NSObject
/// Start removing old files
- (void)start;
/// Stop removing old files
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Used to encapsulate a data source (e.g. HRRR, GFS).
SWIFT_CLASS("_TtC7Terrier13TrrDataSource")
@interface TrrDataSource : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;

SWIFT_CLASS("_TtC7Terrier8TrrError")
@interface TrrError : NSError
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


@class TrrColorMap;

SWIFT_PROTOCOL("_TtP7Terrier20TrrIPrecipController_")
@protocol TrrIPrecipController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier19TrrIRadarController_")
@protocol TrrIRadarController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier27TrrISingleChannelController_")
@protocol TrrISingleChannelController <TrrIController>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@end


SWIFT_PROTOCOL("_TtP7Terrier25TrrITemperatureController_")
@protocol TrrITemperatureController <TrrISingleChannelController>
@end


SWIFT_PROTOCOL("_TtP7Terrier15TrrITimeTracker_")
@protocol TrrITimeTracker
@property (nonatomic, readonly) NSTimeInterval curEpoch;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)play;
- (void)poke;
- (void)addDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Pass in an epoch and return the value interpolated along our range.
/// This is useful for a slider.
- (double)interpolateSimpleWithEpoch:(NSTimeInterval)epoch SWIFT_WARN_UNUSED_RESULT;
- (void)removeDelegateWithDelegate:(NSObject * _Nonnull)delegate;
- (void)shutdown;
@end


SWIFT_PROTOCOL("_TtP7Terrier22TrrTimeTrackerDelegate_")
@protocol TrrTimeTrackerDelegate <NSObject>
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

@class MaplyTexture;

SWIFT_PROTOCOL("_TtP7Terrier18TrrIWindController_")
@protocol TrrIWindController <TrrIController, TrrTimeTrackerDelegate>
/// Enable wind trails.  Independent of the velocity layer.
@property (nonatomic) BOOL enableTrails;
/// Total number of points in the trails.   This determines the size of the buffers used and the memory requirement.
@property (nonatomic) NSInteger trailPoints;
/// The largest allowable value of <code>maxTrailCount</code>, as determined by the memory reserved by <code>trailPoints</code>.
/// The number of trails is limited to <code>trailPoints</code> divided by the number of trail points in a buffer, <code>maxTrailSize</code>
@property (nonatomic, readonly) NSInteger maxMaxTrailCount;
/// Limit the number of trails to a number smaller than the limit as determined above.
/// This does not reduce memory usage, but may improve rendering framerate.
@property (nonatomic) NSInteger maxTrailCount;
/// Minimum lifetime of trails in seconds.
/// Trail lifetimes are set to a random value between the min and max to avoid excessive visual “flocking”
@property (nonatomic) NSTimeInterval trailLifetimeMin;
/// Max lifetime of trails in seconds
@property (nonatomic) NSTimeInterval trailLifetimeMax;
/// Limit the number of points in a trail to a value smaller than the space reserved.
@property (nonatomic, readonly) NSInteger maxTrailSize;
/// This value sets the lower limit of the number of points that must be established in a trail.  If the trail reaches the edge
/// of the screen or turns too sharply, it will be discarded and the trail will be set up in a new location on the next frame.
@property (nonatomic) NSInteger minTrailSize;
/// Width of trails in pixels
@property (nonatomic) float trailWidth;
/// Length of each trail cell in pixels.
@property (nonatomic) float trailAdvanceRate;
/// Maximum turn to allow per point (radians)
/// Only applies when more restrictive than the limit calculated from <code>atan(advance / width)</code>
@property (nonatomic) float turnAngleLimit;
/// Maximum cumulative under-turn before stopping trail advance (sum of dot-products)
@property (nonatomic) float turnErrorLimit;
/// The texture appears this many times along the trail, i.e., texture Y coordinates run from 0..N.
@property (nonatomic) float texPeriod;
/// Only show every Nth texture instance, assuming <code>texPeriod</code> is larger.
/// e.g., <code>texPeriod=4</code> and <code>texInterval=2</code> would split the length of the trail into four parts and show the texture in
/// the first and third of those parts.
@property (nonatomic) NSInteger texInterval;
/// Rate of texture motion (trail lengths / s)
/// The texture Y coordinate shifts by this amount every second, cycling the application of the texture along the trail.
/// May be negative to reverse the direction of motion. (no, you wouldn’t want to do that)
@property (nonatomic) float texRate;
/// Effect of velocity on tex rate
/// 0: no effect, 1: max velocity = 2x texture rate, 2: max velocity = 3x texture rate, …
@property (nonatomic) float texVelRate;
/// Exponential base of velocity effect, 1 = linear.
/// Nearer to base == 0, the effect increases rapidly near zero velocity then levels off near the maximum.
/// For larger values above 1, the effect increases slowly near zero and more rapidly near the maximum.
@property (nonatomic) float texVelExp;
/// Side-to-side texture offset.  By default, the texture will be centered on the trail, aligned such that the X-axis
/// is perpendicular, with 0 at the left and 1 at the right.
@property (nonatomic) float texOffsetX;
/// Front-to-back texture offset.  Shifts the starting point of the texture placement described by <code>texPeriod</code> and <code>texRate</code>
@property (nonatomic) float texOffsetY;
/// Smallest velocity to consider having a meaningful direction
@property (nonatomic) float minVelocity;
/// Fade-in time when a new trail is established, in seconds.
@property (nonatomic) NSTimeInterval fadeIn;
/// Fade-out time when a trail expires, in seconds.
@property (nonatomic) NSTimeInterval fadeOut;
/// How quickly zooming causes established trails to expire.
/// At 1, the remaining time for a trail is reduced by the ratio between the new and old scale.
@property (nonatomic) float scaleResetFactor;
/// Log base for shape modulation function
@property (nonatomic) float shapeParamB;
/// Exponent for shape modulation function
@property (nonatomic) float shapeParamP;
/// Limit for shape modulation function
@property (nonatomic) float shapeParamS;
/// Base color and alpha multiplier for trails
@property (nonatomic, strong) UIColor * _Nonnull trailColor;
/// Color map for trails (including alpha opacity)
@property (nonatomic, strong) TrrColorMap * _Nullable trailColorMap;
/// If true, the trail color map is scaled to the source data range
@property (nonatomic) BOOL scaleTrailColorMap;
/// Apply a new trail color map, optionally scaling [0,1] to the source data range
- (void)setTrailColorMap:(TrrColorMap * _Nullable)_ scaleToRange:(BOOL)scaleToRange;
/// Primary texture for trails (when not using arrows)
@property (nonatomic, strong) MaplyTexture * _Nullable trailTexture;
/// Reset all existing trails over the following time interval.
- (void)resetTrailsWithOverTime:(NSTimeInterval)overTime;
/// Snap to time frames.
/// True to only show a single time at once, switching abruptly when the target time reaches half way between frames.
/// False to interpolate between times.
@property (nonatomic) BOOL animationSnap;
/// Get or override the display of time animation.
/// This overrides the animating state of the time tracker. Use <code>resetAnimatingTime</code> to restore that.
@property (nonatomic) BOOL isAnimatingTime;
/// Reset to using animation state from time tracker
- (void)resetAnimatingTime;
/// If true, fixed arrows are shown instead of wind trails while animating through time.
@property (nonatomic) BOOL animationArrows;
/// If arrows are enabled, this is the texture used. (it doesn’t have to be an arrow).
/// The texture colors will be multiplied through the trail color map, so the texture should be white.
@property (nonatomic, strong) MaplyTexture * _Nullable arrowTexture;
/// The fraction of trails to convert into arrows.  All of them is really dense.
@property (nonatomic) float arrowShowFrac;
/// Length of the arrows (pixels)
@property (nonatomic) float arrowLength;
/// Width of the arrows (pixels)
@property (nonatomic) float arrowWidth;
/// Enable the background layer of wind velocity.  Independent of wind trails.
@property (nonatomic) BOOL enableVelocity;
/// Mapping of wind velocities to colors for the background layer.
@property (nonatomic, strong) TrrColorMap * _Nullable velocityColorMap;
/// If true, the velocity color map is scaled to the source data range
@property (nonatomic) BOOL scaleVelocityColorMap;
/// Apply a new velocity color map, optionally scaling [0,1] to the source data range
- (void)setVelocityColorMap:(TrrColorMap * _Nullable)_ scaleToRange:(BOOL)scaleToRange;
/// Interpolation mode for rendering the off-screen variable target to the screen.
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
/// Whether to use our custom interpolation shader (true) or the built-in Metal interpolator (false)
/// to sample wind data for velocity rendering.
@property (nonatomic) BOOL visualInterpCustom;
/// The interpolation mode used for rendering data into the off-screen variable target.
/// Data interpolation always uses the custom, no-data-aware interpolation implementation.
/// In practice, this can use the slower bicubic interpolation  because <code>TrrIVarController.renderScale</code>
/// reduces the amount of data being processed.
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
/// Opacity factor blended into the alpha channel of the colors used for both trails and velocity
@property (nonatomic) float opacity;
/// If set, we’ll do data values at the center of the screen
@property (nonatomic) BOOL centerSampling;
/// Return two values for wind (U and V) or nothing
- (NSArray<NSNumber *> * _Nonnull)getCenterSample SWIFT_WARN_UNUSED_RESULT;
/// Offline rendering mode changes a little output math
@property (nonatomic) BOOL offlineMode;
@end

typedef SWIFT_ENUM(NSInteger, TrrInterpolationMode, open) {
  TrrInterpolationModeNearest = 0,
  TrrInterpolationModeBilinear = 1,
  TrrInterpolationModeBicubic = 2,
};


/// Displays a loading progress bar under whatever parent UIView you give it.
SWIFT_CLASS("_TtC7Terrier17TrrLoaderProgress")
@interface TrrLoaderProgress : NSObject
/// Start tracking loading and rendering to the tracking image
- (void)start;
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7Terrier9TrrMinMax")
@interface TrrMinMax : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Precipitation controller displays precipitation type data.
SWIFT_CLASS("_TtC7Terrier19TrrPrecipController")
@interface TrrPrecipController : TrrBaseController <TrrIPrecipController, TrrTimeTrackerDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// Set the color map used for display.  This will map from precipitation types to colors.
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end


/// Radar overlay
SWIFT_CLASS("_TtC7Terrier18TrrRadarController")
@interface TrrRadarController : TrrBaseController <TrrIRadarController, TrrTimeTrackerDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

@protocol TrrServiceDelegate;

/// Access to the Terrier Service.  By default this points to a public stack, but you may
/// have your own modifications (e.g. CDNs, authorization, etc).
SWIFT_CLASS("_TtC7Terrier10TrrService")
@interface TrrService : NSObject
@property (nonatomic, copy) NSString * _Nonnull stackName;
@property (nonatomic, readonly, copy) NSString * _Nonnull baseURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull manifestURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull tileURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull vectorURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull mapURL;
@property (nonatomic, readonly) NSInteger apiVersion;
@property (nonatomic, strong) id <TrrServiceDelegate> _Nullable delegate;
- (nonnull instancetype)initWithStackName:(NSString * _Nonnull)stackName OBJC_DESIGNATED_INITIALIZER;
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Fill in this protocol to be notified when the TrrService is ready.
SWIFT_PROTOCOL("_TtP7Terrier18TrrServiceDelegate_")
@protocol TrrServiceDelegate <NSObject>
- (void)serviceReadyWithService:(TrrService * _Nonnull)service;
- (void)serviceFailed;
@end


/// Generic controller for single-channel data like temperature
SWIFT_CLASS("_TtC7Terrier26TrrSingleChannelController")
@interface TrrSingleChannelController : TrrBaseController <TrrISingleChannelController, TrrTimeTrackerDelegate>
@property (nonatomic, strong) TrrColorMap * _Nullable colorMap;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end


/// Used to describe how many time slices of data and over what range.
/// The actual data manifest needs to be fetched with this in mind.
SWIFT_CLASS("_TtC7Terrier16TrrSourceCadence")
@interface TrrSourceCadence : NSObject
/// The oldest data to consider, relative to the current time
@property (nonatomic, readonly) NSTimeInterval minTimeOffset;
/// The newest data to consider, relative to the current time
@property (nonatomic, readonly) NSTimeInterval maxTimeOffset;
/// The maximum number of time slices (frames) to consider
@property (nonatomic, readonly) NSInteger maxTimeSlices;
/// If the cadence has been resolved, this is set to when
@property (nonatomic, readonly) NSTimeInterval now;
/// Sort out absolute time from relative time and return it
- (TrrSourceCadence * _Nonnull)resolve SWIFT_WARN_UNUSED_RESULT;
/// Clip against the other cadence and return the results
- (TrrSourceCadence * _Nonnull)clip:(TrrSourceCadence * _Nullable)clip SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithMinTimeOffset:(NSTimeInterval)minTimeOffset maxTimeOffset:(NSTimeInterval)maxTimeOffset maxTimeSlices:(NSInteger)maxTimeSlices;
- (nonnull instancetype)init;
@end


/// Temperature overlay
SWIFT_CLASS("_TtC7Terrier24TrrTemperatureController")
@interface TrrTemperatureController : TrrSingleChannelController <TrrITemperatureController>
@end

@protocol MaplyRenderControllerProtocol;

/// Time Tracker is used to set and update the displayed time amongst a group
/// of delegates.  You can add or remove delegates to the list that get notified interactively.
/// In general, when the time changes, the delegates are notified.
SWIFT_CLASS("_TtC7Terrier14TrrTimeTracker")
@interface TrrTimeTracker : MaplyActiveObject <TrrITimeTracker>
/// Current time for display.  This is what the Tracker is telling all the delegates is the current time.
/// This may be updated externally, or it may be updated as part of an ongoing play.
/// Time is in seconds since 1970.
@property (nonatomic) NSTimeInterval curEpoch;
/// Return true if we’re animating.
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
/// Start animating if we’re not already.
- (void)play;
/// Send a new round of updates to watchers.
/// You may want to do this if you’ve added a new one, though the Tracker will handle that for you.
- (void)poke;
/// Pass in an epoch and return the value interpolated along our range.
/// This is useful for a slider, where the returned value will be in the range 0 to 1.
- (double)interpolateSimpleWithEpoch:(NSTimeInterval)epoch SWIFT_WARN_UNUSED_RESULT;
/// Add a delegate watcher for changes to the values.
/// The delegate will get called with every change to the value, including during an active play().
/// As such, you might want to throttle updates on your side if they’re expensive.
- (void)addDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Remove a delegate watcher.
/// Delegate will no longer be called for Tracker events.
- (void)removeDelegateWithDelegate:(NSObject * _Nonnull)delegate;
/// Stop sending updates to delegates.
- (void)shutdown;
- (BOOL)hasUpdate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithViewController:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class MaplyBaseViewController;
@class NSData;
@class MaplyRenderTarget;

/// The Variable Controler marshalls data sources for a given
/// variable.
SWIFT_CLASS("_TtC7Terrier16TrrVarController")
@interface TrrVarController : NSObject <MaplySnapshotDelegate>
- (BOOL)needSnapshot:(NSTimeInterval)now viewC:(MaplyBaseViewController * _Nonnull)viewC SWIFT_WARN_UNUSED_RESULT;
- (void)snapshot:(NSData * _Nonnull)snapshotData;
- (MaplyRenderTarget * _Nullable)renderTarget SWIFT_WARN_UNUSED_RESULT;
- (CGRect)snapshotRect SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The manifest gives us details on a given variable (e.g. Temperature)
/// from a particular source (e.g. GFS).  This includes the spatial extents,
/// details about its encoding, and the time slices available.
SWIFT_CLASS("_TtC7Terrier14TrrVarManifest")
@interface TrrVarManifest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC7Terrier14TrrVarManifest9TimeSlice")
@interface TimeSlice : NSObject
@property (nonatomic, readonly) NSTimeInterval forecastEpoch;
@property (nonatomic, readonly) NSTimeInterval runEpoch;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The Variable Source handles the logic for fetching data from a specific
/// data source (e.g. HRRR, 2m_temperature) and rendering it to screen space
SWIFT_CLASS("_TtC7Terrier12TrrVarSource")
@interface TrrVarSource : MaplyActiveObject <TrrTimeTrackerDelegate, TrrVarManifestDelegate>
/// Notify us before the controller so that the frames are up-to-date
@property (nonatomic, readonly) NSInteger manifestDelegatePriority;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
- (void)manifestDidLoadWithManifest:(TrrVarManifest * _Nonnull)manifest success:(BOOL)success;
- (nonnull instancetype)initWithViewController:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Wind Controller handles the visual display of the wind surface and particles.
SWIFT_CLASS("_TtC7Terrier17TrrWindController")
@interface TrrWindController : TrrBaseController <TrrIWindController>
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
/// Enable wind trails
@property (nonatomic) BOOL enableTrails;
/// Enable velocity background
@property (nonatomic) BOOL enableVelocity;
@property (nonatomic) BOOL isAnimatingTime;
- (void)resetAnimatingTime;
@property (nonatomic) enum TrrInterpolationMode varInterpMode;
@property (nonatomic) BOOL animationSnap;
@property (nonatomic) enum TrrInterpolationMode visualInterpMode;
@property (nonatomic) BOOL visualInterpCustom;
/// Total number of points (not trails)
@property (nonatomic) NSInteger trailPoints;
/// Width of trails in pixels
@property (nonatomic) float trailWidth;
/// Length of trail cells in pixels
@property (nonatomic) float trailAdvanceRate;
/// Maximum turn to allow per segment (radians)
@property (nonatomic) float turnAngleLimit;
/// Maximum cumulative under-turn before stopping trail advance (sum of dot-products)
@property (nonatomic) float turnErrorLimit;
/// Base lifetime of trails
@property (nonatomic) NSTimeInterval trailLifetimeMin;
/// Fractional lifetime variation
@property (nonatomic) NSTimeInterval trailLifetimeMax;
/// Number of texture applications along the trail
@property (nonatomic) float texPeriod;
/// Rate of texture motion (trail lengths / s)
@property (nonatomic) float texRate;
/// Effect of velocity on tex rate
/// 0: no effect, 1: max velocity = 2x texture rate, 2: max velocity = 3x texture rate
@property (nonatomic) float texVelRate;
/// Exponent on velocity effect
/// 1: linear, 0.1: 0.5=>0.76, 0.01: 0.5=>0.9
@property (nonatomic) float texVelExp;
/// Texture offsets
@property (nonatomic) float texOffsetX;
@property (nonatomic) float texOffsetY;
/// Only show every Nth texture instance
@property (nonatomic) NSInteger texInterval;
/// Don’t set up very short trails, e.g., if we hit the edge of available data
@property (nonatomic) NSInteger minTrailSize;
@property (nonatomic, readonly) NSInteger maxTrailSize;
@property (nonatomic, readonly) NSInteger maxMaxTrailCount;
@property (nonatomic) NSInteger maxTrailCount;
@property (nonatomic) float minVelocity;
@property (nonatomic) NSTimeInterval fadeIn;
@property (nonatomic) NSTimeInterval fadeOut;
@property (nonatomic) float scaleResetFactor;
@property (nonatomic) float shapeParamB;
@property (nonatomic) float shapeParamP;
@property (nonatomic) float shapeParamS;
@property (nonatomic, strong) UIColor * _Nonnull trailColor;
@property (nonatomic, strong) TrrColorMap * _Nullable trailColorMap;
@property (nonatomic) BOOL scaleTrailColorMap;
- (void)setTrailColorMap:(TrrColorMap * _Nullable)map scaleToRange:(BOOL)scaleToRange;
@property (nonatomic, strong) MaplyTexture * _Nullable trailTexture;
@property (nonatomic, strong) MaplyTexture * _Nullable arrowTexture;
/// Whether to show static arrows in place of trails while animating timeslices
@property (nonatomic) BOOL animationArrows;
/// The fraction of trails to show as arrows
@property (nonatomic) float arrowShowFrac;
/// Length of arrows (pixels)
@property (nonatomic) float arrowLength;
/// Width of arrows (pixels)
@property (nonatomic) float arrowWidth;
/// Offline mode changes the output logic a little
@property (nonatomic) BOOL offlineMode;
@property (nonatomic, strong) TrrColorMap * _Nullable velocityColorMap;
@property (nonatomic) BOOL scaleVelocityColorMap;
- (void)setVelocityColorMap:(TrrColorMap * _Nullable)map scaleToRange:(BOOL)scaleToRange;
@property (nonatomic) float opacity;
- (void)resetTrailsWithOverTime:(NSTimeInterval)overTime;
+ (id <TrrIWindController> _Nonnull)createWithLevel:(NSString * _Nullable)level service:(TrrService * _Nonnull)service tracker:(id <TrrITimeTracker> _Nonnull)tracker viewC:(id <MaplyRenderControllerProtocol> _Nonnull)viewC SWIFT_WARN_UNUSED_RESULT;
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
- (void)stop;
/// Set if you want an up to date center value sample.
/// There’s a performance cost, so we need to turn it on.
@property (nonatomic) BOOL centerSampling;
/// Return a sample from the middle fo the screen.
- (NSArray<NSNumber *> * _Nonnull)getCenterSample SWIFT_WARN_UNUSED_RESULT;
/// TrrTimeTrackerDelegate implementation
- (void)trackerUpdateWithTracker:(id <TrrITimeTracker> _Nonnull)tracker epoch:(NSTimeInterval)epoch;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
